%% ScriptConfiguration
% -- Script which configures directories and names of files during computations.
% -- ScriptConfiguration.m should be configure according to descriptions below.
% -- User have to run ScripConfiguration.m before start of first computations 

%% STRUCTURE
%  modeldir
%     |-> <model.name.1>
%     |-> <model.name.2>
%     ...
%     |-> <model.name.i>   
%             |-> Input
%                   |-> parameters_names.csv %%% OPTIONAL
%                   |-> variables_names.csv  %%% OPTIONAL
%                   |-> <computation.name.1>
%                   ...
%                   |-> <computation.name.j>
%                           |-> parameters.csv %% initial values of
%                           parameters
%                           |-> variables.csv  %% initial values of
%                           variables
%                   ...
%                   |-> <computation.name.m>
%             |-> MATLAB
%                   |-> <functions used in model>
%                   |-> symbolic % folder generated by createODE
%                           |-> <model.name>.m
%                           |-> <model.name>_jacobian_dpar.m
%                           |-> <model.name>_jacobian_dvar.m
%                           |-> <model.name>_jacobian_MRE.m  %%% OPTIONAL
%             |-> Output
%                   |-> 
%     ... 
%     |-> <model.name.n-1>
%     |-> <model.name.n>

%% Main directories
 
%modeldirlinux = '/media/knt/D/KN/ClustSense/ClusteringIdentifiability/Models/'; 
modeldirlinux = '/home/piotrek/Documents/heterogeneity_model/heterogeneity/scripts/MATLAB/models/'; 

% full directory of folder with definitions of models on Linux / MAC OS
modeldirwin = 'Y:\PiotrT\cellcyclemodel\MATLAB\models\';
% full directory of folder with definitions of models on Windows

if ispc()
    modeldir = modeldirwin;
else
    modeldir = modeldirlinux;
end

addpath(modeldir);

%% Format of data
%delimeter = '\t';
delimeter = ',';
% delimeter used in input and output csv files

%% Model definition directories
%modelmatlabdir = @(name) [modeldir, name, '/MATLAB/']; 
modelmatlabdir = @(name) [modeldir, name]; 
% directory of folder with input to MATLAB computations

modelsymbolicdir = @(name) [modelmatlabdir(name), '/symbolic/'];
% directory of symbolic files used in analysis

modelsbmldir = @(name) [modeldir, name, '/SBML/'];
% directory of SBML file for model name (not used)

modeloutputdir = @(name) [modeldir, name, '/Output/'];
% directory of output for model name

%% Model files names

%modelodedir = @(name) [name '_all_equations'];
%  name of MATLAB file with model definition
modelodedir = @(name) [name];

%modeljacpardir = @(name) [name '_all_equations_jacobian_dpar'];
%  name of MATLAB file with jacobian of parameters
modeljacpardir = @(name) [name '_jacobian_dpar'];

%modeljacvardir = @(name) [name '_all_equations_jacobian_dvar'];
modeljacvardir = @(name) [name '_jacobian_dvar'];
%  name of MATLAB file with jacobian of variables

%% Input directories

parametersdir = @(name, input) [modeldir, name, '/Input/', input, '/', 'parameters.csv'];
% directory of a priori parameters values

parametersnamesdir = @(name) [modeldir, name, '/Input/', 'parameters_names.csv'];
% directory of  parameters names (optional)

variablesdir = @(name, input) [modeldir, name, '/Input/', input, '/', 'variables.csv'];
% directory of a priori initial variables values

variablesnamesdir = @(name) [modeldir, name, '/Input/', 'variables_names.csv'];
% directory of variables names (optional)